CREATE TABLE targetedms.ExcludedPrecursors
(
    rowId INT IDENTITY(1, 1) NOT NULL,
    precursorIdentifier NVARCHAR(1000),
    Container ENTITYID NOT NULL,

    CONSTRAINT PK_EXCLUDEDPRECURSORS_ROWID PRIMARY KEY (rowId),
    CONSTRAINT FK_EXCLUDEDPRECURSORS_CONTAINER FOREIGN KEY (Container) REFERENCES core.Containers(EntityId),
    CONSTRAINT UQ_EXCLUDEDPRECURSORS_PRECURSOR_IDENTIFIER UNIQUE (precursorIdentifier)
);
GO

CREATE INDEX IX_EXCLUDEDPRECURSORS_CONTAINER ON targetedms.ExcludedPrecursors (Container);
GO